# Alembic migration script template
"""Add start and end time to tests

Revision ID: ac0f77243e53
Revises: 0860c0900501
Create Date: 2026-08-09 23:42:51.982257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0f77243e53'
down_revision: Union[str, None] = '0860c0900501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tests', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'end_time')
    op.drop_column('tests', 'start_time')
    # ### end Alembic commands ###
